# values.yaml
replicaCount: 1
image:
  repository: rodybothe2/java-app-bootcamp
  tag: v1.0.0
  pullPolicy: IfNotPresent
service:
  name: java-app-service
env:
  DB_USER: admin

controller:
  service:
    enabled: true
  ingressClass: "nginx"
  publishService:
    enabled: true