helm install -n ms -f values/redis-values.yaml rediscart charts/redis
helm install -n ms -f values/email-service-values.yaml emailservice charts/microservice
helm install -n ms -f values/cart-service-values.yaml cartservice charts/microservice
helm install -n ms -f values/currency-service-values.yaml currencyservice charts/microservice
helm install -n ms -f values/payment-service-values.yaml paymentservice charts/microservice
helm install -n ms -f values/recommendation-service-values.yaml recommendationservice charts/microservice
helm install -n ms -f values/productcatalog-service-values.yaml productcatalogservice charts/microservice
helm install -n ms -f values/shipping-service-values.yaml shippingservice charts/microservice
helm install -n ms -f values/ad-service-values.yaml adservice charts/microservice
helm install -n ms -f values/checkout-service-values.yaml checkoutservice charts/microservice
helm install -n ms -f values/frontend-values.yaml frontendservice charts/microservice
