#!/usr/bin/env groovy
pipeline {
    agent any

    stages {
        stage('build application') {
            steps {
                script {
                    echo "building the application..."
                }
            }
        }

        stage('build image') {
            steps {
                script {
                    echo "building the docker image..."
                }
            }
        }

        stage('deploy') {
            steps {
                script {
                    echo 'deploying docker image...'
                    withKubeConfig([credentialsId: 'lke-credentials', serverUrl: 'https://ad8x5g97-924d-6h33-et37-5hkf99n0klf.eu-central-2.linodelke.net']) {
                        sh 'kubectl create deployment nginx-deployment --image=nginx'
                    }
                }
            }
        }
    }
}
