apiVersion: v1
kind: Service
metadata:
  name: java-maven-app-service
  labels:
    app: $APP_NAME
spec:
  selector:
    app: j$APP_NAME
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
