# templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-java-app-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
        - name: java-container
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
              - containerPort: 8080
          env:
            - name: DB_USER
              value: {{ .Values.env.DB_USER }}
            - name: DB_SERVER
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-java-configmap
                  key: DB_SERVER
            - name: DB_PWD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-java-secret
                  key: DB_PWD
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-java-configmap
                  key: DB_NAME
---
# templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
#  name: java-app
spec:
  selector:
    app: java-app
#  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
#      nodePort: 30005
