#!/usr/bin.env groovy

pipeline {
    agent any
    tools {
        maven 'Maven'
    }
    environment {
        IMAGE_NAME = 'rodybothe2/demo-app:java-maven-1.0'
    }
    stages {
        stage("build app") {
            steps {
                echo 'build app jar...'
                buildJar();
            }
        }
        stage("build image") {
            steps {
                script {
                    echo "Building docker image..."
                    buildImage(env.IMAGE_NAME)
                    dockerLogin()
                    dockerPush(env.IMAGE_NAME)
                }
            }
        }

        stage("deploy") {
            steps {
                script {
                    echo "Deploying image to EC2"
                    def dockerCmd = "docker run -p 3080:3080 -d ${IMAGE_NAME}"
                    sshagent(['ec2-server-key']) {
                        sh "ssh -o StrictHostKeyChecking=no ec2-user@3.121.174.25 ${dockerCmd}"
                    }
                }
            }
        }
    }
}

def buildJar() {
    sh "mvn clean package"
}

def buildImage(imageName) {
    sh "docker build -t ${imageName} ."
}

def dockerLogin() {
    withCredentials([usernamePassword(credentialsId: 'docker-registry-creds', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
        sh "docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}"
    }
}
def dockerPush(imageName) {
    sh "docker push ${imageName}"
}
