#!/bin/bash

kubectl create secret docker-registry my-ecr-secret \
--docker-server=someawsurl.dkr.ecr.eu-central-1.amazonaws.com \
--docker-username=AWS \
--docker-password=token \
--docker-email=rodybothe2
