apiVersion: v1
kind: Config
clusters:
  - cluster:
      certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJTE9hbkFnL1NtSk13RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TkRBeE1USXhPVE0yTXpOYUZ3MHpOREF4TURreE9UUXhNek5hTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURBMXF1eWZ0ZWV0cDkwOFpMQnNCM01kb0ZjaStQTXpOWHpTV1cyRHY4R01GY0lVUjRVa1N1SjF3WW4KZDNqVU1GL0VaQnVVM1VHOWJlZUtGZ2VuZUcySmZRZnh3MmtzV0ZrS1dqQ0JSb3hSVlFQWTkrME9UdnNicFBsTgp3d01QclA5STFZejFwWEN0djl1eGp5WXhscWFnWWhIWFNMblRzMjk5SmpTRmtVMHgrQm1PeU5jRDBOQ1ZST0IrCkRsQ3NNeEQ2aGh0T1NaUVlUdU9SVnpFUktvUFRTaVZaSW81Q29TQTFPZXNHOWI0RE9RbTlOUkpHbTU3VW9RYUcKOTVzZ0ZROG9qZWpzREduQVJMTzd5czNNV05WS0NZN0hFdSs1bHdXdXU4eTV3OVRsN2lPVEx2QkNqNkNOaHBFVwpRMU4rdE4wK3RaKzRRL3liMnBHSFBsSm9CL096QWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTWnd1ekF3UFpwelV6alZvc3hzZ21WV09Db0FUQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQnJIa3p2dVpJOApENmo0cEo4OUE4TlZld1I4b0s5eHhyU0dLekh2UysrdThTdFpSVnlMREdTcWM2V0NsS2JFeStTSWNEYTQyWGVWCjRVVjZaSXROaTFPREdRZFFoQ2pwTWN6UHlYdkhMMVJHMWpDcE9XcVdxREZXeE5vQkVPbDlFc2NRaWJCYlFkTFcKYTdMNHBXODJycUJzcmVQQUpqNWRkUEZmWjJZRVk0SGFwN0NIaVo1aU1qUjl4d3B0NkRSRlZTTTJkendXL0s5YgpWMCtsYVZVbHVpVlY0bU94UGRYL0FpYStibHczVmFZSTJGc0gvYTJOT3JCOHFhNlNxUnRwMklEWE1ybjFpUmcyCmZSaXI2R0JKYzVSVDZ0aDIvVVlrNHpROEVIYXZyNWxwanRlSEVJd3h3Y04vR1poWmdmTnREVldRcW1yZ0JKcVAKTDd4c3RPSVRrQnR4Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      server: https://F3E627452ECEBD05672CC22E127792E8.gr7.eu-central-1.eks.amazonaws.com
    name: kubernetes
contexts:
  - context:
      cluster: kubernetes
      user: aws
    name: aws
current-context: aws
users:
  - name: aws
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1beta1
        command: /usr/bin/aws-iam-authenticator
        args:
          - "token"
          - "-i"
          - "demo-cluster2"