---
- name: Deploy app in new namespace
  hosts: localhost
  tasks:
    - name: Create a k8s namespace
      kubernetes.core.k8s:
        name: my-app
        api_version: v1
        kind: Namespace
        state: present
        kubeconfig: /Users/rodybothe/Documents/devops-course-nana/15-Ansible/Demo-projects/AnsibleK8S/kubeconfig_myapp-eks-cluster.yaml
    - name: Deploy nginx ap
      kubernetes.core.k8s:
        src: /Users/rodybothe/Documents/devops-course-nana/k8s-files/nginx.yaml
        state: present
        kubeconfig: /Users/rodybothe/Documents/devops-course-nana/15-Ansible/Demo-projects/AnsibleK8S/kubeconfig_myapp-eks-cluster.yaml
        namespace: my-app