apiVersion: v1
clusters:
  - cluster:
      certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJYUM1Q1QrZG51cmd3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TkRBeE1URXhOalV3TURkYUZ3MHpOREF4TURneE5qVTFNRGRhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURSOVZickw1OHFyaVhNZWZqVk95aXM3NGxMMjlJMXlraDJhSGs5MkRHV0FpL0g0Y0JFZ3JsaTg2Q3oKMGVPOFZVaVhZSHlQYm5DTGRvRXBLbFhZdHg4YVJzZXJtSFJhZERnY3NXRm9nSUQwT2tSbnZmQUhWa1VIdEJLbQpoR0NxL21kUjFDb1IxVHhkdDQ4UHBOd0pkbVNURGhjU1hFS2hNeDcvcWczamdhSEFKellHLzNkODZ0OUpSUm5WCkIvV2FFQUdCMTJodEtndFVuSDdJbHdsUWJZei9GVVNWeFc0V1QzMW51TlJMVENjOFdIaDF5cmlBV2lHWDNtTXkKdmZYaGYvbTMxOGY2alhKRldvdk1jMXZSQ0ovQnhvRG9hQktsVUdlV2xEN3liR2t2VVVMWnNWS0RES1NGaW5mMgowRVhNSkVZL1lLWHpqYVhaRkx0dTByUHZGU0dCQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTZ1JweFJQL29sTTV0Q3QvT0lVK3kzRHNhTVRUQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQkw5RFNydCtOMQpyUjdQV3lNSk9qSmlUdVBNaUJ4aUtsSW5seDBRbXVPc2RJUFIwY2FYbmFIOWM0NHNOWjEyVWlweEh4T21ldFJwCnlralRHb3FpOWs4NE4zWUE5SldTNjhpMUxnTjBIRENVQWFmTXY1VGV5NVdrTFlJY21YOFhac3BSalJYVG9HV2YKc29BbThnVkRhMnlKYmFORFl1elRxRlJ2SnFnTGVxUmhCWHlJWVBkTXpsY3BNWlQ0Rk1TUllmNGZSWFA3bGRzOQpwLzg5U3orV2dMUTAwa0VCV2dpWExIdmNsMEcxbkd3QitqMFBEMy8vL2tTWUd0OGJSQm9MeGl5RTlTVmVWYzhiCjQ5TldxN3hXaHU4cGFvMTRJdWR4ektqdDJDMVlHNnQrbHRPb3Zyc2tLenpBRElDUVU3eWR4TnBFeFEvUEhuQVgKV1I3cEZvLzUxVXJCCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      server: https://8463E679A07A847F36E85D59015756E1.gr7.eu-central-1.eks.amazonaws.com
    name: arn:aws:eks:eu-central-1:826861811879:cluster/eks-cluster-test
  - cluster:
      certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJTE9hbkFnL1NtSk13RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TkRBeE1USXhPVE0yTXpOYUZ3MHpOREF4TURreE9UUXhNek5hTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURBMXF1eWZ0ZWV0cDkwOFpMQnNCM01kb0ZjaStQTXpOWHpTV1cyRHY4R01GY0lVUjRVa1N1SjF3WW4KZDNqVU1GL0VaQnVVM1VHOWJlZUtGZ2VuZUcySmZRZnh3MmtzV0ZrS1dqQ0JSb3hSVlFQWTkrME9UdnNicFBsTgp3d01QclA5STFZejFwWEN0djl1eGp5WXhscWFnWWhIWFNMblRzMjk5SmpTRmtVMHgrQm1PeU5jRDBOQ1ZST0IrCkRsQ3NNeEQ2aGh0T1NaUVlUdU9SVnpFUktvUFRTaVZaSW81Q29TQTFPZXNHOWI0RE9RbTlOUkpHbTU3VW9RYUcKOTVzZ0ZROG9qZWpzREduQVJMTzd5czNNV05WS0NZN0hFdSs1bHdXdXU4eTV3OVRsN2lPVEx2QkNqNkNOaHBFVwpRMU4rdE4wK3RaKzRRL3liMnBHSFBsSm9CL096QWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTWnd1ekF3UFpwelV6alZvc3hzZ21WV09Db0FUQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQnJIa3p2dVpJOApENmo0cEo4OUE4TlZld1I4b0s5eHhyU0dLekh2UysrdThTdFpSVnlMREdTcWM2V0NsS2JFeStTSWNEYTQyWGVWCjRVVjZaSXROaTFPREdRZFFoQ2pwTWN6UHlYdkhMMVJHMWpDcE9XcVdxREZXeE5vQkVPbDlFc2NRaWJCYlFkTFcKYTdMNHBXODJycUJzcmVQQUpqNWRkUEZmWjJZRVk0SGFwN0NIaVo1aU1qUjl4d3B0NkRSRlZTTTJkendXL0s5YgpWMCtsYVZVbHVpVlY0bU94UGRYL0FpYStibHczVmFZSTJGc0gvYTJOT3JCOHFhNlNxUnRwMklEWE1ybjFpUmcyCmZSaXI2R0JKYzVSVDZ0aDIvVVlrNHpROEVIYXZyNWxwanRlSEVJd3h3Y04vR1poWmdmTnREVldRcW1yZ0JKcVAKTDd4c3RPSVRrQnR4Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      server: https://F3E627452ECEBD05672CC22E127792E8.gr7.eu-central-1.eks.amazonaws.com
    name: demo-cluster2.eu-central-1.eksctl.io
contexts:
  - context:
      cluster: arn:aws:eks:eu-central-1:826861811879:cluster/eks-cluster-test
      user: arn:aws:eks:eu-central-1:826861811879:cluster/eks-cluster-test
    name: arn:aws:eks:eu-central-1:826861811879:cluster/eks-cluster-test
  - context:
      cluster: demo-cluster2.eu-central-1.eksctl.io
      user: iam-root-account@demo-cluster2.eu-central-1.eksctl.io
    name: iam-root-account@demo-cluster2.eu-central-1.eksctl.io
users:
  - name: arn:aws:eks:eu-central-1:826861811879:cluster/eks-cluster-test
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1beta1
        args:
          - --region
          - eu-central-1
          - eks
          - get-token
          - --cluster-name
          - eks-cluster-test
          - --output
          - json
        command: aws
  - name: iam-root-account@demo-cluster2.eu-central-1.eksctl.io
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1beta1
        args:
          - token
          - -i
          - demo-cluster2
        command: aws-iam-authenticator
        env:
          - name: AWS_STS_REGIONAL_ENDPOINTS
            value: regional
          - name: AWS_DEFAULT_REGION
            value: eu-central-1
